# Generated by Django 4.1 on 2022-09-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email_non_indexed",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
